
# Config:
# Intended for setting up scripts 
# outside the scope of vps-package


---
- hosts: webservers
  become: true
  vars_files:
    - ./vars/vars.yml

  tasks:

    - name: add apt key
      apt_key:
        url: https://repos.insights.digitalocean.com/sonar-agent.asc
        state: present

    - name: "Check if do-agent is installed"
      package_facts:
        manager: "auto"
    - name: "do-agent result"
      debug:
          msg: "do-agent not found, installing"
      include_tasks: tasks/install-do-agent.yml
      when: "'do-agent' not in ansible_facts.packages"
