---
- hosts: webservers
  become: true
  vars_files:
    - ./vars/vars.yml

  tasks:

    - name: Add Docker GPG apt Key
      apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker packages
      apt: update_cache=yes pkg={{item}} state=latest
      with_items:
        - docker-ce
        - docker-compose

    - name: Install Docker Module for Python
      pip:
        name: docker